// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLB0Wn89A8qutm6GQRzlp9FAvVuEw3EU',
    appId: '1:910018982029:web:1a74b816c726394726f2c4',
    messagingSenderId: '910018982029',
    projectId: 'realtime-a5389',
    authDomain: 'realtime-a5389.firebaseapp.com',
    databaseURL: 'https://realtime-a5389-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-a5389.firebasestorage.app',
    measurementId: 'G-69CDF9XMJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjPt3-X0XNCoLiko87Yq7PmIKHNGWXdwo',
    appId: '1:910018982029:android:a1549b40e7fa3af226f2c4',
    messagingSenderId: '910018982029',
    projectId: 'realtime-a5389',
    databaseURL: 'https://realtime-a5389-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-a5389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_kw1QFYG_kWbK1_coiQFo18XMqgTrKj0',
    appId: '1:910018982029:ios:551bead217a58a3026f2c4',
    messagingSenderId: '910018982029',
    projectId: 'realtime-a5389',
    databaseURL: 'https://realtime-a5389-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-a5389.firebasestorage.app',
    iosBundleId: 'com.example.realtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_kw1QFYG_kWbK1_coiQFo18XMqgTrKj0',
    appId: '1:910018982029:ios:551bead217a58a3026f2c4',
    messagingSenderId: '910018982029',
    projectId: 'realtime-a5389',
    databaseURL: 'https://realtime-a5389-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-a5389.firebasestorage.app',
    iosBundleId: 'com.example.realtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArLB0Wn89A8qutm6GQRzlp9FAvVuEw3EU',
    appId: '1:910018982029:web:3cadfe8f44a9ab8926f2c4',
    messagingSenderId: '910018982029',
    projectId: 'realtime-a5389',
    authDomain: 'realtime-a5389.firebaseapp.com',
    databaseURL: 'https://realtime-a5389-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-a5389.firebasestorage.app',
    measurementId: 'G-MKZRTNYJPG',
  );
}
